name: surrealdb
description: SurrealDB client written in pure dart. Auto reconnect, Typed functions
version: 0.6.2
repository: https://github.com/duhanbalci/surrealdb_flutter

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  web_socket_channel: ^2.3.0

dev_dependencies:
  test: ^1.22.2
  lints: ^2.0.1
