name: surrealdb
description: SurrealDB client written in pure dart. Auto reconnect, Typed functions
version: 0.4.8
repository: https://github.com/duhanbalci/surrealdb_flutter

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  web_socket_channel: ^2.2.0

dev_dependencies:
  test: ^1.21.7
  lints: ^2.0.1
