name: Tests
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  runner-job:
    strategy:
      matrix:
        version: [latest,nightly]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - name: Install dependencies
        run: dart pub get
      - name: Analyze project source
        run: dart analyze
      - name: Start surrealdb
        run: docker run -d -p 8000:8000 surrealdb/surrealdb:${{ matrix.version }} start --user root --pass root
      - name: Run tests   
        run: dart test
